name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js from .nvmrc
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'

    - name: Install yarn
      run: npm install -g yarn@1.15.2

    - name: Install dependencies
      run: yarn install --ignore-engines

    - name: Run unit tests
      run: ./node_modules/.bin/ng test --browsers=ChromeHeadless --watch=false

    - name: Start server
      run: ./node_modules/.bin/ng serve > ng_serve.log 2>&1 &

    - name: Run e2e tests
      run: |
        sleep 10
        ./node_modules/.bin/ng e2e
